name: Deploy to Render

on:
  push:
    branches: [ main ]  # Adjust this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Deploy to Render
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      run: |
        # Check if service exists
        SERVICE_ID=$(curl -H "Authorization: Bearer $RENDER_API_KEY" https://api.render.com/v1/services | jq -r '.[] | select(.name == "my-app-name") | .id')

        if [ -z "$SERVICE_ID" ]; then
          # Create new service
          SERVICE_ID=$(curl -X POST -H "Authorization: Bearer $RENDER_API_KEY" -H "Content-Type: application/json" \
            -d '{
              "name": "my-app-name",
              "type": "web_service",
              "env": "docker",
              "region": "oregon",
              "plan": "free",
              "branch": "main",
              "repo": "https://github.com/gwgshivam-uytrdf234/ytvideodownload-with-ffmpeg",
              "autoDeploy": "yes"
            }' \
            https://api.render.com/v1/services | jq -r '.id')
          echo "Created new service with ID: $SERVICE_ID"
        else
          echo "Service already exists with ID: $SERVICE_ID"
        fi

        # Trigger deploy
        curl -X POST -H "Authorization: Bearer $RENDER_API_KEY" https://api.render.com/v1/services/$SERVICE_ID/deploys